### ISSUE TITLE
Repeating toot?

### ISSUE THREAD

**Issue by Zerolemis** [dariusk/rss-to-activitypub#20]
For the last few days the account I created always send more than one (even 5 or 10) repeating feed at the same time. Is there any way to fix it?
For example: https://bots.tinysubversions.com/u/AfricanAsianLiteratureBot

**Comment by dariusk** [comment]
Thanks, I believe I fixed the bug in this commit: 45e1362aa2528fe0b84d0d81d83b855dd6a08065

I'll keep this bug open for a while until I've gotten confirmation that the dupes are gone. (If they are gone for you please let me know here!)

**Comment by Zerolemis** [comment]
Sorry, the problem is still not fixed... here's another example:
https://bots.tinysubversions.com/u/theinitium 
it has just tooted 11 same toots at the same time.
And also here: 
https://bots.tinysubversions.com/u/BookCat 
it has just tooted every toot 4 times.

**Comment by dariusk** [comment]
@Zerolemis Can you give me the specific URL of a few repeated toots? If you click the time stamp on the toot it should take you to a url like bots.tinysubversions.com/m/abcdef123 , if I could have a few of those that would be great.

**Comment by dariusk** [comment]
Never mind, I think I have fixed it NOW. Sorry about that.

**Comment by Zerolemis** [comment]
Yes! I think it has been nicely fixed. Thank you so much!

**Comment by dariusk** [comment]
Reopening this per discussion in #22. I have no idea why this has regressed....

**Comment by dariusk** [comment]
Okay, I think what is happening is that there are enough feeds now that it takes more than 5 minutes to process them all; this means that I end up spawning overlapping processes that duplicate the sending of messages. I've reduced the update time on the server to once every 15 minutes and that SHOULD solve this problem. I'm going to wait a few hours and see if the problem feeds no longer do this.

Eventually what I should probably do is just process all feeds and then start over once that's done, a constant rotating queue.

**Comment by dariusk** [comment]
> Eventually what I should probably do is just process all feeds and then start over once that's done, a constant rotating queue.

Fixed this by updating the server to use a message queuing system.
